# Generated by Django 4.2.3 on 2023-07-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catageory',
            new_name='category',
        ),
    ]
